### ISSUE TITLE
Weird behaviour when using options

### ISSUE THREAD

**Issue by PalleZingmark** [import-io/s3-deploy#10]
This script will return `All files uploaded.`, but no files will actually be uploaded.

``` javascript
"scripts": {
    "deploy": "s3-deploy --gzip './public/**' --cwd './public/' --region Ireland --bucket mybucket"
}
```

These scripts will all return `Upload error: TimeoutError: Missing credentials in config`, and no files will  be uploaded.

``` javascript
"scripts": {
    "deploy": "s3-deploy './public/**' --cwd './public/' --region Ireland --bucket mybucket --gzip"
}
```

``` javascript
"scripts": {
    "deploy": "s3-deploy './public/**' --cwd './public/' --region Ireland --bucket mybucket"
}
```

**Comment by domderen** [comment]
I don't think `--region Ireland` is a valid value. I think you have to use `eu-west-1` as the value. All the regions are described here: http://docs.aws.amazon.com/general/latest/gr/rande.html

**Comment by PalleZingmark** [comment]
Yes, that is indeed correct, but for the example scripts above it really doesn't matter. 
Still the same weird behaviour.

**Comment by domderen** [comment]
Not sure what to tell you. Below I attach the example of how I use this package successfully in multiple projects:
```
"deploy": "s3-deploy './dist/**' --cwd './dist/' --region $AWS_REGION --bucket $BUCKET_NAME/$BUILD_NUM --gzip --cache 31536000",
```

I know it's a stupid question, but are you sure that you `public` dir isn't empty?

**Comment by PalleZingmark** [comment]
Yes, I'm sure it isn't empty. :) 

If I move `--gzip` to the end, I indeed get the same error instead of it telling me _all files uploaded_, so It seems I'm actually messing something up with the credentials? 

I set the credentials in a `.env` with the rest of the configs which loads into process.env using `dotenv`. But when the deploy-script runs they seem to get lost. 
How can I make sure s3-deploy gets the correct process.env?

**Comment by domderen** [comment]
s3-deploy works as a normal bash script, so you would most likely need to set the keys in the normal environment variables. Or you could use the AWS standard '~/.aws/credentials' file to set the keys. 

I also might be talking bull shit, as I never used dotenv, but from description it looks like it only works for bootstrapping applications, not scripts?
