### ISSUE TITLE
Regression when uploading a file that contains a hypen

### ISSUE THREAD

**Issue by AnilRedshift** [import-io/s3-deploy#14]
Bug: Try to upload the following file: `/Users/foo/myrepo/myrepo-0.1.2.tgz`

expected: `myrepo-0.1.2` gets uploaded to S3
Actual: `-0.1.2.tgz` gets uploaded.

This is a regression from https://github.com/import-io/s3-deploy/commit/9a6edb95b941f53a6ea0c831a9a6a87596faea5e

reverting this commit fixes the bug.

**Comment by AnilRedshift** [comment]
I don't know the exact scenario from the original bug, but my suspicion is that what you want is something similar to `url.resolve(path.join(foo, bar))`

**Comment by domderen** [comment]
Hey, thanks for catching that, the changes were reverted in version 0.7.2. Will look into the initial commit to see if there is some other way to fix the problem it was intended to fix.

**Comment by vpatel-gb** [comment]
It worked fine in windows after these changes, so looks like people might have faced issues with Mac. 
(I didn't check in Mac).

The issue is with inherent behavior of OSes. In windows the physical directory separator is "\" and in Mac "/"

**Comment by AnilRedshift** [comment]
Closing this issue as the revert fixed it.
