### ISSUE TITLE
--deleteRemoved option

### ISSUE THREAD

**Issue by carstensaltus** [import-io/s3-deploy#28]
Could the --deleteRemoved option be added in the up coming release?

**Comment by afontcu** [comment]
+1. Or any other way to clean up the existing directory.

**Comment by domderen** [comment]
Sounds like a good idea, feel free to create a PR for this one ;)

**Comment by brianeletype** [comment]
I needed this functionality too so I put something together.  It's in PR #30

**Comment by domderen** [comment]
Nice, thanks @brianeletype looks good! I've merged the changes, and it should automatically deploy after the build completes.
