### ISSUE TITLE
Is it possible to specify the file location?

### ISSUE THREAD

**Issue by Bodacious** [import-io/s3-deploy#29]
My dist file structure is:

```
dist
├── myfile.min.js
└── index.html
```

How can I upload this to S3 so that the bucket contains a dir named `v2` with `my_file.js` in it?

**Comment by domderen** [comment]
Hey @Bodacious,

This library is not meant to create additional directories on upload, or rename your files on the fly. I would recommend performing those operations using standard CLI tools before uploading your files to S3.

Hope that helps.

Cheers,
Dom

**Comment by Bodacious** [comment]
OK, thanks Dom
