### ISSUE TITLE
Upload folders recursively in Windows ?

### ISSUE THREAD

**Issue by sebastienfi** [import-io/s3-deploy#37]
On Windows, when doing something like `s3-deploy "./*" --cwd "./" --region REGION_NAME --bucket BUCKET_NAME` only the files under `./` get uploaded. The contained folders (`./folder/`) and the files of these folders remains untouched, which I was not expecting.

**Comment by domderen** [comment]
@sebastienfi Shouldn't that be `s3-deploy "./**/*"` to tell the system to get all files and subdirectories?

**Comment by sebastienfi** [comment]
Thank you @domderen , that solved the issue.
