### ISSUE TITLE
Feature to validate bucket immutability

### ISSUE THREAD

**Issue by joeljeske** [import-io/s3-deploy#38]
I am interested in a feature that would check for conflicts before upload and validate that the bucket object matches the local copy. Essentially, I want to ensure immutability and it does not seem like S3 could do this natively. 

Does that make sense? Is this a feature you would want to add to this project? I would be more than happy to make a PR for this if you think it would be a good addition to this project.

**Comment by domderen** [comment]
Hey, 

I'm not sure I fully understand what you mean by checking for conflicts? Would it mean that the library should not upload a file, if that would overwrite an already existing file on S3?

Could you provide a bit more details on how would you see such feature working?

**Comment by joeljeske** [comment]
Sorry, yes. Basically, I would like to make my bucket immutable; I only want to be able to create files, never change or delete them. As far as I know, S3 does not support this. I want to use this tool to enforce my immutability. Upon deployment, I want this tool to determine which local files are new and thus needs to be uploaded, and which local files already exist in the bucket. If they already exist in the bucket, I want this tool to check the etag hash. If they are the same, skip the upload. If they are different, display a message indicating that a change was detected but the file was not uploaded. 

My build process before deployment  hashes all the files or puts them in a unique folder, but I want to ensure this as part of deployment. 

Does that make any sense?

I made a PR that does this when the parameter —preventUpdates is passed. I’d love for you to take a look and give feedback as to it’s validity in this project or other stylistic concerns you may have.

**Comment by domderen** [comment]
Thanks for the PR, I've gone though the changes, and those look good. I've merged the PR, and deployed it in version 0.10.0.
