### ISSUE TITLE
CloudFront invalidation

### ISSUE THREAD

**Issue by karolisgrinkevicius** [import-io/s3-deploy#45]
Do you have the plan in near future to create an invalidation for cloudfront distribution after deployment to s3 is completed?

**Comment by domderen** [comment]
Hey Karolis,

We don't have any immediate plan to add such functionality to this package, but we do accept and appreciate external contributions. It sounds like an interesting feature, so if you have an idea how it could work, feel free to prepare a PR.

Cheers,
Dom

**Comment by karolisgrinkevicius** [comment]
Hi @domderen. Thanks for quick response. I did not dig into aws api yet but once find time capacity for that I promise will create a pull request.
