### ISSUE TITLE
s3-deploy command not found

### ISSUE THREAD

**Issue by chrisdel101** [import-io/s3-deploy#46]
Deploy failed with the above error. 

My string looks like this:  `s3-deploy './dist/**' --cwd './dist/' --region US-WEST-2 --bucket my-bucket-name-30-goes-here`

The main reason I opened this issue was because when I type `s3-deploy` into bash I get the same error. The package is installed as dev dependency. I assumed typing `s3-deploy` would be like typing `node`? A command that takes further inputs.

**Comment by domderen** [comment]
Hey,

Do you have the `s3-deploy` dependency installed globally? By default dependencies installed as dev deps are not available on your path, so typing `s3-deploy` into a terminal, won't work. You can either install `s3-deploy` as a global dependency with `npm install -g s3-deploy` or you can use the dependency from your `node_modules/.bin` directory. If you are in the project directory, where `s3-deploy` is installed as dev dep, you can run it by doing `./node_modules/.bin/s3-deploy ...`.

Hope that helps. Will close this ticket, but feel free to reopen if you have additional questions.
