### ISSUE TITLE
Ability to set signatureVersion

### ISSUE THREAD

**Issue by farwayer** [import-io/s3-deploy#5]
Some regions require AWS4-HMAC-SHA256 authentication scheme
http://stackoverflow.com/a/26538266/2175114
Unfortunately it is not configurable via aws config file.

Can you add ability to set `signatureVersion` option please?

**Comment by domderen** [comment]
This should now be available in `0.5.1` version of the package.

Sorry for the late response.

**Comment by farwayer** [comment]
Thank you a lot!
