### ISSUE TITLE
It´s says that the upload is finished but I don´t see any files on my bucket

### ISSUE THREAD

**Issue by ThiagoMiranda** [import-io/s3-deploy#50]
Hi..
I´m trying to use s3-deploy but it isn´t working.

My command:
`s3-deploy './public/**' --cwd './public/' --bucket my-bucket-name --deleteRemoved --gzip`

I get this message on my console:
```unix
► Target S3 bucket: my-bucket-name (us-east-1 region)
► Gzip: gzip
► Private: false
Upload finished
No files to delete.
Done in 1.06s.
```
But the files aren´t there. If I have previously files they are deleted successfully so I don´t think that is a credentials problem. Does this package supports somekind of plugin to check it out?
Or do I need any "special" configuration on my bucket? Does it need to be public?

Thanks!

**Comment by domderen** [comment]
This might be caused by how windows uses backslashes rather than forward slashed. I would try changing your command to use backslashes and see if it helps.

**Comment by ThiagoMiranda** [comment]
I´ve tried but none of this worked. Where I can debug directly which files did the package loaded to upload?

**Comment by ThiagoMiranda** [comment]
@domderen I´ve used the cross-env package and it worked nicely!
`cross-env s3-deploy './public/**' --cwd './public/' --bucket bkt-hml-site-institucional --deleteRemoved --gzip` 

Thanks for the attention and help :)

**Comment by domderen** [comment]
Great, glad to hear it was resolved ;)
