### ISSUE TITLE
Follow better SemVer

### ISSUE THREAD

**Issue by koresar** [import-io/s3-deploy#52]
The package is using `0` as a MAJOR SemVer number. The [standard](https://semver.org/) (which npm does follow) says: 
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

This means that package API stability should not be trusted until it reaches v1.

Since this is pretty stable, robust and awesome tool can we please follow better SemVer and have next release as v1.0.0?

**Comment by domderen** [comment]
Hey, it makes sense, I've deployed current version as 1.0.0, and we can go from there. Out of curiosity, which corporation had a problem with using a package that was in version <1.0.0? ;)

**Comment by koresar** [comment]
It's less of a corporation more like a human problem.

People tend to think that upgrades from `0.N` to `0.N+1` are backwards compatible. Thus, they do so. It results with production issues. However, those were breaking changes.

Even `0.0.N` to `0.0.N+1` can be breaking according to SemVer. But people think it's a bugfix release.

**Comment by domderen** [comment]
Makes sense, should be easier now. Closing this issue.

**Comment by koresar** [comment]
Btw, this tool is so good, I recommend it to other people here: https://stackoverflow.com/a/50248177/188475

**Comment by domderen** [comment]
Thanks for that, I'm glad you like the tool ;)
