### ISSUE TITLE
what is --gzip?

### ISSUE THREAD

**Issue by koresar** [import-io/s3-deploy#55]
Hello.
Great tool!

Question regarding this sentence.
> Specifying `--gzip` will gzip all files before sending them.

Sending from where to where?
* From tool to S3? or
* From S3 to website users?

Thanks.

**Comment by domderen** [comment]
It gzips all specified files on your hard drive before uploading them to S3, and adds appropriate `Content-Encoding: gzip` Metadata attribute on uploaded elements in S3, so that when they are opened in the browser, the browser knows to decompress them first before displaying.

**Comment by koresar** [comment]
Thank you!

Sorry for using your excellent explanation in the PR: #56

**Comment by domderen** [comment]
No worries, thanks for the contribution ;)
