### ISSUE TITLE
--distId without --invalidate will throw error

### ISSUE THREAD

**Issue by DiegoRBaquero** [import-io/s3-deploy#67]
I recently updated and now I get the error `Cannot read property 'split' of undefined` at https://github.com/import-io/s3-deploy/blob/master/src/deploy.js#L240

Fixed by adding `--invalidate '/*'`

Just pointing this out :)

**Comment by hsz** [comment]
Regarding docs - it should:

>  Defaults to ['/']. 

Default value is not provided anywhere.

**Comment by ErikEklund** [comment]
Just ran into this too. Confirmed that adding `'/*'` as path after `--invalidate` fixes the issue.
