### ISSUE TITLE
s3-deploy command not found

### ISSUE THREAD

**Issue by dotconnor** [import-io/s3-deploy#78]
When installing via yarn, yarn doesn't correctly parse the `bin` property in `package.json`, resulting in the binary never being created.

**Comment by c-nichols** [comment]
I'm having a similar problem -- s3-deploy never makes it into `node_modules/.bin/`.  Were you able to solve this issue?

**Comment by dotconnor** [comment]
@c-nichols No I was not, I ended up just creating a basic script to do what I needed.

**Comment by domderen** [comment]
Hey, I don't have experience with yarn, so not sure what would be necessary to fix this issue. If someone has experience with yarn, and knows how to fix it, PRs are always welcome.

**Comment by c-nichols** [comment]
I actually think this is an issue with Yarn.  Just opened up an issue on Yarn with some more detail: https://github.com/yarnpkg/yarn/issues/6753

**Comment by jbblanchet** [comment]
Not sure if it's a bug or a feature in yarn yet, but the issue seems to be with the `.bin` folder in the source. Renaming the folder to `bin` and changing the reference in package.json fixed the problem for me. Will also comment on the yarn issue.

**Comment by srilq** [comment]
This PR #93 seems to have broken `s3-deploy` with npm. Oh no!

`node_modules/s3-deploy/.bin/s3-deploy: no such file or directory`

**Comment by srilq** [comment]
Ah, false alarm. We are just using the wrong path.

Fix: `node_modules/s3-deploy/.bin/s3-deploy` –> `node_modules/.bin/s3-deploy`

**Comment by domderen** [comment]
Yes, from npm v4 I think, all the binaries are in `node_modules/.bin/<BINARY_NAME>` path. Will close this issue for now.
