### ISSUE TITLE
Only upload files that have changed?

### ISSUE THREAD

**Issue by achingbrain** [import-io/s3-deploy#94]
Is it possible to only upload files who's ETag has changed? I keep hitting AWS `PUT` request limits as `s3-deploy` re-uploads files that don't change between builds like images and other static assets.

The docs for `--preventUpdates` says:

> Use this parameter to validate that the object .. already matches the ETag hash and thus is skipped and not uploaded.

which sounds like the one but the implementation appears to [skip the upload entirely](https://github.com/import-io/s3-deploy/blob/e2348592ec75f092065bb7e32c4158d94ed63a75/src/deploy.js#L139) if `--preventUpdates` is set and the file exists.

**Comment by achingbrain** [comment]
Actually I think the combination of `IfNoneMatch` and checking for `304` response codes does this.

**Comment by mrchief** [comment]
@achingbrain Could you explain how you got around this? I'm facing this issue even though my hashes differ. 

```
Update prevented: local hash is 4d69d8c9c1a819d000ea07c67c3317f5 but bucket hash is "9901ee03a73a61be9cf9c5d4197f53e2"
```
